(function(){
var view=document.getElementById('view'), modal=document.getElementById('modalRoot'), toastRoot=document.getElementById('toastRoot'), title=document.getElementById('pageTitle'), crumb=document.getElementById('crumb');
var data={reservations:[['BK-1048','Olivia Carter','101','Oct 07 → Oct 10','Checked in','$840'],['BK-1047','Daniel Lee','102','Oct 07 → Oct 09','Confirmed','$520'],['BK-1046','Emma Wilson','103','Oct 08 → Oct 12','Confirmed','$980'],['BK-1045','Noah Smith','104','Oct 09 → Oct 11','Pending','$460']],rooms:[]};
for(var i=1;i<=12;i++)data.rooms.push({id:100+i,type:i%3?'Deluxe':'Suite',status:i<5?'Occupied':i<8?'Reserved':i===8?'Cleaning':'Available',guest:i<5?['Olivia Carter','Daniel Lee','Emma Wilson','Noah Smith'][i-1]:''});
function save(){localStorage.setItem('stayflow-v3',JSON.stringify(data))}
function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
function pill(s){var c=/Occupied|Checked|Paid|Available|Completed/.test(s)?'green':/Pending|Cleaning/.test(s)?'orange':/Cancelled|Maintenance/.test(s)?'red':'blue';return '<span class="pill '+c+'">'+esc(s)+'</span>'}
function toast(s){var x=document.createElement('div');x.className='toast';x.textContent=s;toastRoot.appendChild(x);setTimeout(function(){x.remove()},2200)}
function table(){return '<div class="table-wrap"><table class="table"><thead><tr><th>Booking</th><th>Guest</th><th>Room</th><th>Stay</th><th>Status</th><th>Amount</th></tr></thead><tbody>'+data.reservations.map(function(r){return '<tr><td><b>'+r[0]+'</b></td><td>'+esc(r[1])+'</td><td>'+r[2]+'</td><td>'+r[3]+'</td><td>'+pill(r[4])+'</td><td><b>'+r[5]+'</b></td></tr>'}).join('')+'</tbody></table></div>'}
function shell(name,html){title.textContent=name;crumb.textContent=name==='Dashboard'?'Overview':'Operations';view.innerHTML=html}
function dashboard(){shell('Dashboard','<div class="hero"><div><h2>Good morning, Hotel Admin 👋</h2><p>Here’s what is happening across Grand Aurora today.</p></div><div class="actions"><button class="btn" data-action="calendar">View calendar</button><button class="btn primary" data-action="new-booking">+ New reservation</button></div></div><div class="grid stats"><div class="card stat"><div class="stat-head">Occupancy <span class="stat-icon">◒</span></div><strong>72%</strong><span class="trend up">↑ 6.4% vs last week</span></div><div class="card stat"><div class="stat-head">Today arrivals <span class="stat-icon">⇥</span></div><strong>18</strong><span class="trend up">8 checked in</span></div><div class="card stat"><div class="stat-head">Departures <span class="stat-icon">⇥</span></div><strong>12</strong><span class="trend">4 pending</span></div><div class="card stat"><div class="stat-head">Revenue <span class="stat-icon">$</span></div><strong>$12.8k</strong><span class="trend up">↑ 9.2% this month</span></div></div><div class="grid dashboard-grid"><div class="card"><div class="card-head"><h3>Revenue overview</h3><span>Last 7 days · $58.4k</span></div><div class="card-body"><div class="bars">'+[38,55,47,72,63,88,76].map(function(n,i){return '<div class="bar-col"><div class="bar" style="--h:'+n+'%"></div><small>'+['M','T','W','T','F','S','S'][i]+'</small></div>'}).join('')+'</div></div></div><div class="card"><div class="card-head"><h3>Room occupancy</h3><span>Today</span></div><div class="card-body occupancy"><div class="donut"><b>72%</b></div><div class="legend"><div><i></i>Occupied <b>36</b></div><div><i class="gray"></i>Available <b>18</b></div><div><i class="gray"></i>Reserved <b>8</b></div><div><i class="gray"></i>Cleaning <b>4</b></div></div></div></div></div><div class="card table-card"><div class="card-head"><h3>Recent reservations</h3><button class="btn" data-section="Reservations">View all</button></div>'+table()+'</div>')}
function reservations(){shell('Reservations','<div class="hero"><div><h2>Reservations</h2><p>Manage arrivals, departures and booking status.</p></div><button class="btn primary" data-action="new-booking">+ New reservation</button></div><div class="card table-card">'+table()+'</div>')}
function calendar(){var h='<div class="hero"><div><h2>Room calendar</h2><p>14-day occupancy view.</p></div><button class="btn primary" data-action="new-booking">+ New reservation</button></div><div class="card calendar"><div class="cal-grid"><div class="cal-head">Room</div>';for(var d=7;d<=20;d++)h+='<div class="cal-head">Oct '+d+'</div>';data.rooms.forEach(function(r){h+='<div class="cal-room">'+r.id+'<br><small>'+r.type+'</small></div>';for(var j=0;j<14;j++)h+='<div>'+(r.status==='Occupied'&&j<4?'<div class="booking">'+esc(r.guest)+'</div>':r.status==='Reserved'&&j>1&&j<6?'<div class="booking orange">Reserved</div>':'')+'</div>'});h+='</div></div>';shell('Calendar',h)}
function rooms(){shell('Rooms','<div class="hero"><div><h2>Rooms</h2><p>Live inventory and room state.</p></div><button class="btn primary" data-action="add-room">+ Add room</button></div><div class="grid room-grid">'+data.rooms.map(function(r){return '<div class="card room"><div class="room-top"><span class="room-num">'+r.id+'</span>'+pill(r.status)+'</div><div class="room-type">'+r.type+'</div><div class="room-meta"><span>'+esc(r.guest||'No guest')+'</span><button class="btn" data-room="'+r.id+'">Manage</button></div></div>'}).join('')+'</div>')}
function guests(){var g=[['Olivia Carter','olivia@example.com','101'],['Daniel Lee','daniel@example.com','102'],['Emma Wilson','emma@example.com','103'],['Noah Smith','noah@example.com','104'],['Sophia Brown','sophia@example.com','205']];shell('Guests','<div class="hero"><div><h2>Guests</h2><p>Profiles, rooms and contact details.</p></div><button class="btn primary" data-action="add-guest">+ Add guest</button></div><div class="card table-card"><div class="table-wrap"><table class="table"><thead><tr><th>Guest</th><th>Email</th><th>Room</th><th>Action</th></tr></thead><tbody>'+g.map(function(x){return '<tr><td><b>'+x[0]+'</b></td><td>'+x[1]+'</td><td>'+x[2]+'</td><td><button class="btn" data-action="guest">Open profile</button></td></tr>'}).join('')+'</tbody></table></div></div>')}
function housekeeping(){shell('Housekeeping','<div class="hero"><div><h2>Housekeeping</h2><p>Prioritize room turnover and service tasks.</p></div><button class="btn primary" data-action="add-task">+ New task</button></div><div class="card table-card"><div class="table-wrap"><table class="table"><thead><tr><th>Room</th><th>Guest</th><th>Task</th><th>Priority</th><th>Status</th></tr></thead><tbody><tr><td>101</td><td>Olivia Carter</td><td>Clean room</td><td>'+pill('High')+'</td><td><button class="btn success" data-action="complete">Mark complete</button></td></tr><tr><td>104</td><td>Noah Smith</td><td>Refresh towels</td><td>'+pill('Normal')+'</td><td><button class="btn success" data-action="complete">Mark complete</button></td></tr></tbody></table></div></div>')}
function payments(){shell('Payments','<div class="hero"><div><h2>Payments</h2><p>Track settled, pending and refunded transactions.</p></div><button class="btn primary" data-action="payment">+ Record payment</button></div><div class="grid stats"><div class="card stat"><div class="stat-head">Collected</div><strong>$42.6k</strong><span class="trend up">↑ 8.1%</span></div><div class="card stat"><div class="stat-head">Pending</div><strong>$3.8k</strong><span class="trend">12 transactions</span></div><div class="card stat"><div class="stat-head">Refunded</div><strong>$1.2k</strong><span class="trend down">3 transactions</span></div><div class="card stat"><div class="stat-head">Crypto</div><strong>$6.4k</strong><span class="trend up">USDT supported</span></div></div>')}
function reports(){shell('Reports','<div class="hero"><div><h2>Reports</h2><p>Operational KPIs for management review.</p></div><button class="btn" data-action="export">Export report</button></div><div class="grid dashboard-grid"><div class="card"><div class="card-head"><h3>Monthly performance</h3></div><div class="card-body"><div class="bars">'+[44,61,54,70,77,69,91,83].map(function(n,i){return '<div class="bar-col"><div class="bar" style="--h:'+n+'%"></div><small>W'+(i+1)+'</small></div>'}).join('')+'</div></div></div><div class="card"><div class="card-head"><h3>Key metrics</h3></div><div class="card-body"><p><b>ADR</b> $184</p><p><b>RevPAR</b> $132</p><p><b>Average stay</b> 2.8 nights</p><p><b>Cancellation</b> 4.2%</p></div></div></div>')}
function settings(){shell('Settings','<div class="hero"><div><h2>Settings</h2><p>Hotel profile and interface preferences.</p></div><button class="btn primary" data-action="save-settings">Save changes</button></div><div class="card" style="padding:20px"><div class="form-grid"><div class="field"><label>Hotel name</label><input id="hotelName" value="Grand Aurora"></div><div class="field"><label>Default currency</label><select><option>USD — US Dollar</option><option>EUR — Euro</option><option>USDT — Tether</option></select></div><div class="field"><label>Timezone</label><select><option>America/Chicago</option><option>Asia/Tehran</option><option>UTC</option></select></div><div class="field"><label>Reservation alerts</label><select><option>Enabled</option><option>Disabled</option></select></div></div></div>')}
var pages={Dashboard:dashboard,Reservations:reservations,Calendar:calendar,Rooms:rooms,Guests:guests,Housekeeping:housekeeping,Payments:payments,Reports:reports,Settings:settings};
function nav(s){if(!pages[s])s='Dashboard';document.querySelectorAll('.nav a[data-section]').forEach(function(a){a.classList.toggle('active',a.getAttribute('data-section')===s)});shell(s,'');pages[s]();if(history.replaceState)history.replaceState(null,'','#'+s)}
function newBooking(){modal.innerHTML='<div class="modal-backdrop" data-close><div class="modal"><div class="modal-head"><h3>Create reservation</h3><button class="close" data-close>×</button></div><div class="modal-body"><div class="form-grid"><div class="field"><label>Guest name</label><input id="fGuest" placeholder="e.g. Sarah Miller"></div><div class="field"><label>Room</label><select id="fRoom">'+data.rooms.filter(function(r){return r.status==='Available'}).map(function(r){return '<option>'+r.id+'</option>'}).join('')+'</select></div><div class="field"><label>Check-in</label><input id="fIn" type="date"></div><div class="field"><label>Check-out</label><input id="fOut" type="date"></div><div class="field"><label>Amount</label><input id="fAmount" placeholder="$650"></div><div class="field"><label>Status</label><select id="fStatus"><option>Confirmed</option><option>Pending</option><option>Checked in</option></select></div></div></div><div class="modal-foot"><button class="btn" data-close>Cancel</button><button class="btn primary" id="createBooking">Create reservation</button></div></div></div>';document.getElementById('createBooking').onclick=function(){var g=document.getElementById('fGuest').value.trim();if(!g)return toast('Guest name is required');data.reservations.unshift(['BK-'+(1050+data.reservations.length),g,document.getElementById('fRoom').value||'—',(document.getElementById('fIn').value||'Today')+' → '+(document.getElementById('fOut').value||'Later'),document.getElementById('fStatus').value,document.getElementById('fAmount').value||'$0']);save();modal.innerHTML='';toast('Reservation created');nav('Reservations')}}
document.addEventListener('click',function(e){var sec=e.target.closest('[data-section]');if(sec){e.preventDefault();nav(sec.getAttribute('data-section'));return}var act=e.target.closest('[data-action]');if(act){var a=act.getAttribute('data-action');if(a==='home')nav('Dashboard');else if(a==='calendar')nav('Calendar');else if(a==='new-booking')newBooking();else if(a==='complete')toast('Task completed');else if(a==='export')toast('Report export prepared');else if(a==='save-settings')toast('Settings saved');else if(a==='add-room'||a==='add-guest'||a==='add-task'||a==='payment'||a==='guest')toast('Action is ready');}if(e.target.closest('[data-close]'))modal.innerHTML=''});
document.getElementById('globalSearch').addEventListener('input',function(e){var q=e.target.value.toLowerCase();if(q.length>2&&data.reservations.some(function(r){return (r[0]+r[1]+r[2]).toLowerCase().indexOf(q)>-1}))nav('Reservations')});
document.getElementById('menuBtn').onclick=function(){document.getElementById('sidebar').classList.toggle('open')};
window.addEventListener('hashchange',function(){nav(location.hash.slice(1)||'Dashboard')});
nav(pages[location.hash.slice(1)]?location.hash.slice(1):'Dashboard');
})();